src/bundle/DependencyInjection/IbexaSolrExtension.php

| **JIRA issue**                          | [IBX-1589](https://issues.ibexa.co/browse/IBX-1589)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#5
- ~Provided automated test coverage.~ // full stack Behat coverage

IBX-1589: Renamed Extension ez_search_engine_solr to ibexa_solr

---

composer.json

```
➜  solr git:(main) ✗ php vendor/bin/phpunit --bootstrap tests/bootstrap.php
PHP Fatal error:  Uncaught Error: Class 'Ibexa\Tests\Solr\Search\TestCase' not found in /home/adamwojs/ibexa/solr/tests/lib/Search/FieldMapper/BoostFactorProviderTest.php:17
Stack trace:
#0 /home/adamwojs/ibexa/solr/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once()
#1 /home/adamwojs/ibexa/solr/vendor/phpunit/phpunit/src/Util/FileLoader.php(54): PHPUnit\Util\FileLoader::load()
#2 /home/adamwojs/ibexa/solr/vendor/phpunit/phpunit/src/Framework/TestSuite.php(384): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /home/adamwojs/ibexa/solr/vendor/phpunit/phpunit/src/Framework/TestSuite.php(482): PHPUnit\Framework\TestSuite->addTestFile()
#4 /home/adamwojs/ibexa/solr/vendor/phpunit/phpunit/src/Util/Configur …
```

Added missing entry for Ibexa\Tests\Solr in composer.json

---

doc/specifications/document_field_mappers.md
src/bundle/DependencyInjection/IbexaSolrExtension.php
src/lib/Container/Compiler/AggregateCriterionVisitorPass.php
src/lib/Container/Compiler/AggregateSortClauseVisitorPass.php
src/lib/Container/Compiler/CoreFilterRegistryPass.php
src/lib/Container/Compiler/EndpointRegistryPass.php
src/lib/Container/Compiler/FieldMapperPass/BlockFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/BlockTranslationFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/ContentFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/ContentTranslationFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/LocationFieldMapperPass.php
src/lib/Container/Compiler/GatewayRegistryPass.php
src/lib/Resources/config/container/solr.yml
src/lib/Resources/config/container/solr/aggregation_result_extractors.yml
src/lib/Resources/config/container/solr/aggregation_visitors.yml
src/lib/Resources/config/container/solr/criterion_visitors.yml
src/lib/Resources/config/container/solr/facet_builder_visitors.yml
src/lib/Resources/config/container/solr/field_mappers.yml
src/lib/Resources/config/container/solr/services.yml
src/lib/Resources/config/container/solr/sort_clause_visitors.yml
tests/bundle/DependencyInjection/IbexaSolrExtensionExtensionTest.php
tests/lib/Container/Compiler/AggregateCriterionVisitorPassTest.php
tests/lib/Container/Compiler/AggregateFacetBuilderVisitorPassTest.php
tests/lib/Container/Compiler/AggregateSortClauseVisitorPassTest.php
tests/lib/Resources/config/cloud.yml
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml

| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.

IBX-1694: Rebranded dependency injection container service tags

---

bin/.travis/init_solr.sh
src/lib/Container/Compiler/FieldMapperPass/BlockFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/BlockTranslationFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/ContentFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/ContentTranslationFieldMapperPass.php
src/lib/Container/Compiler/FieldMapperPass/LocationFieldMapperPass.php
src/lib/Resources/config/container/solr/field_mappers.yml
src/lib/Resources/config/container/solr/services.yml

| **JIRA issue**                          | Follow-up to [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | bug
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | no
#12 introduced incorrect tag name for `ibexa.search.solr.field.mapper.block.translation` and `ibexa.search.solr.field.mapper.content.translation` service tag names.

IBX-1694: Fixed translation mappers service tag name

---

src/lib/Resources/config/container/solr.yml
src/lib/Resources/config/container/solr/aggregation_result_extractors.yml
src/lib/Resources/config/container/solr/services.yml
tests/lib/Resources/config/cloud.yml
tests/lib/Resources/config/common.yml
tests/lib/Resources/config/multicore_dedicated.yml
tests/lib/Resources/config/multicore_shared.yml
tests/lib/Resources/config/single_core.yml
tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/CountryAggregationKeyMapperTest.php

| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern

IBX-1696: Rebranded Container parameters and Config Resolver namespaces

---

src/lib/Container/Compiler/AggregateFacetBuilderVisitorPass.php

Issue link: https://issues.ibexa.co/browse/IBX-2451
`AggregateSortClauseVisitorPass` compiler pass has not been fully migrated.

IBX-2451: migrate service definition and tag name

---

bin/generate-solr-config.sh

| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-3644](https://issues.ibexa.co/browse/IBX-3644) |
| **Type**                                   | improvement |
| **Target Ibexa version** | `v4.2` |
| **BC breaks**                          | no |
This PR aligns usage (help) text of `./bin/generate-solr-config.sh` script with the changes agreed in ezsystems/developer-documentation#1742

IBX-3644: [Doc] Fixed usage text suggested dest dir path

---

composer.json

| **JIRA issue**                          | [IBX-1439](https://issues.ibexa.co/browse/IBX-1439)
| **Requires**                            | ibexa/core#171
| **Type**                                   | feature
| **Target Ibexa version** | `v4.4`
| **BC breaks**                          | not for this package
~This PR updates codebase to use Flysystem v2. Bumped `league/flysystem-memory` to v2.~
This PR drops `league/flysystem-memory` dependency required now by `ibexa/core` (ibexa/core#171).

IBX-1439: Dropped league/flysystem-memory dependency

---

composer.json
src/lib/Query/Common/CriterionVisitor/DateMetadata/PublishedBetween.php
src/lib/Query/Common/CriterionVisitor/DateMetadata/PublishedIn.php

| **JIRA issue**           | [IBX-5061](https://issues.ibexa.co/browse/IBX-5061) |
| **Type**                 | improvement                            |
| **Target Ibexa version** | `v4.3`              |
For legacy search engine, both "published" and "created" targets work for DateMetadata criterion.
Reading through the code, both actually relate to the same column.
However, when working with Solr/Elasticsearch, only "created" criterion works. I assumed that would be because it actually is capable of querying for creation date, but what actually …

IBX-5061: Allowed DateMetadata `published` target

---

src/lib/Container/Compiler/AggregateFacetBuilderVisitorPass.php
src/lib/Query/Common/AggregationVisitor/AbstractRangeAggregationVisitor.php
src/lib/Query/Common/FacetBuilderVisitor/ContentType.php
src/lib/Query/Common/FacetBuilderVisitor/Section.php
src/lib/Query/Common/FacetBuilderVisitor/User.php
src/lib/Query/FacetFieldVisitor.php
src/lib/ResultExtractor.php

| **JIRA issue**           |                                                     |
| **Type**                 | improvement                                         |
| **Target Ibexa version** | `v4.3`                                              |
| **BC breaks**            | no                                                  |
Fixes new PHP 8.2 deprecation notices:
`Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ...`

Fixed deprecation notices in string interpolation with PHP 8.2

---

phpstan-baseline.neon
src/contracts/Query/AggregationVisitor.php
src/lib/Gateway/Native.php
src/lib/Query/Common/AggregationVisitor/DispatcherAggregationVisitor.php
src/lib/Query/QueryConverter.php
tests/lib/Search/Query/Common/AggregationVisitor/AbstractAggregationVisitorTest.php
tests/lib/Search/Query/Common/AggregationVisitor/DispatcherAggregationVisitorTest.php

| **JIRA issue**           | N/A |
| **Type**                 | improvement                             |
| **Target Ibexa version** | `v4.4`
Adds a proper data type for the `AggregationVisitor`, especially since it's not obvious.

Added missing PHPStan declaration for AggregationVisitor

---

phpstan-baseline.neon
src/contracts/Query/AggregationVisitor.php
src/lib/Gateway/EndpointRegistry.php
src/lib/ResultExtractor.php

| **JIRA issue**           | [IBX-4929](https://issues.ibexa.co/browse/IBX-4929) |
| **Type**                 | bug                             |
| **Target Ibexa version** | `v4.x` - please update `x` accordingly              |
- Fix a `@var` syntax (php-like to phpdoc)
- Add missing type to a `@param`
- Move extended syntax from `@param` to `@phpstan-param`

IBX-4929: Fix PhpDoc

---

src/bundle/ApiLoader/BoostFactorProviderFactory.php
src/bundle/ApiLoader/IndexingDepthProviderFactory.php
src/lib/Query/Common/CriterionVisitor/ContentTypeIdentifierIn.php
src/lib/Query/Content/CriterionVisitor/Ancestor.php
src/lib/Query/Location/CriterionVisitor/Ancestor.php

| **JIRA issue**           | - |
| **Type**                 | bug                             |
| **Target Ibexa version** | `v4.5`+|
Fixed issues reported by phpstan in https://github.com/ibexa/solr/actions/runs/6377398486/job/17305988985?pr=51

Fixed issues reported by phpstan

---

composer.json

| **JIRA issue**           | - |
| **Type**                 | bug                             |
| **Target Ibexa version** | `v4.5`|
Plugins are already disallowed in https://github.com/ibexa/solr/blob/main/composer.json#L72-L76.

Removed duplicated config section in composer.json

---

bin/generate-solr-config.sh

| **JIRA issue**           | N/A  |
| **Type**                 | bug                             |
| **Target Ibexa version** | `v4.5`|
Skipped generating `solrconfig.xml` file copies in `bin/generate-solr-config.sh`: `solrconfig.xml.bak` and `solrconfig.xml.bak2`

Skipped generating solrconfig.xml file copies in generate-solr-config.sh

---

composer.json
phpstan-baseline.neon
src/contracts/Test/IbexaSolrTestKernel.php
src/lib/Query/Image/CriterionVisitor/AbstractImageRangeVisitor.php
src/lib/Query/Image/CriterionVisitor/AbstractImageTermsVisitor.php
src/lib/Query/Image/CriterionVisitor/AbstractImageVisitor.php
src/lib/Query/Image/CriterionVisitor/FileSize.php
src/lib/Query/Image/CriterionVisitor/Height.php
src/lib/Query/Image/CriterionVisitor/MimeType.php
src/lib/Query/Image/CriterionVisitor/Orientation.php
src/lib/Query/Image/CriterionVisitor/Width.php
src/lib/Resources/config/container/solr.yml
src/lib/Resources/config/container/solr/criterion_visitors.yml
src/lib/Test/SolrTestContainerBuilder.php
tests/lib/SetupFactory/LegacySetupFactory.php

| **JIRA issue**           | [IBX-6620](https://issues.ibexa.co/browse/IBX-6620) |
| **Type**                 | feature |
| **Target Ibexa version** | `v4.6`               |
| **Requires**            | https://github.com/ibexa/core/pull/284                                         |
This PR adds CriterionVisitors for Image criteria that enables image search in solr engine:
- FileSize
- Height
- Width
- MimeType
- Orientation
There is also added dedicated IbexaTestKernel class for integration tests.

IBX-6620: Added Image criterion visitors

---

.github/init_solr.sh
bin/generate-solr-config.sh
composer.json
src/lib/Handler.php
src/lib/Query/Common/QueryConverter/NativeQueryConverter.php
src/lib/ResultExtractor.php

| **JIRA issue**           | [IBX-6649](https://issues.ibexa.co/browse/IBX-6649) |
| **Type**                 | feature                                             |
| **Target Ibexa version** | `v4.6`                                              |
| **BC breaks**            | no                                                  |
| **Depends on**           | https://github.com/ibexa/core/pull/276              |
Implemented spellchecking in Solr Search Engine based on https://solr.apache.org/guide/solr/latest/query-guide/spell-checking.html
A) Edit Solr configuration: `server/<name>/<...>/solrconfig.xml`:
1. Configure …

IBX-6649: Added support for spell checking

---

src/lib/ResultExtractor/AggregationResultExtractor/RangeAggregationResultExtractor.php
tests/lib/Search/ResultExtractor/AggregationResultExtractor/RangeAggregationResultExtractorTest.php

> [!WARNING]
> # Rebase and remove TMP commit after merging https://github.com/ibexa/core/pull/287
| **JIRA issue**           | [IBX-6827](https://issues.ibexa.co/browse/IBX-6827) |
| **Type**                 | feature                             |
| **Target Ibexa version** | `v4.6` |
See https://github.com/ibexa/core/pull/287

IBX-6827: Aggregation API improvements

---

phpstan-baseline.neon

| **JIRA issue**           | n/a |
| **Type**                 | improvement                             |
| **Target Ibexa version** | `v4.6`              |
Seems we had another release of PHPStan which affected the expected baseline messages. Affects 4.6.x-dev only.

[PHPStan] Regenerated baseline after PHPStan update

---

src/lib/Query/Content/CriterionVisitor/ContentName.php
src/lib/Resources/config/container/solr/criterion_visitors.yml

| **JIRA issue**           | [IBX-7418](https://issues.ibexa.co/browse/IBX-7418) |
| **Type**                 | feature                             |
| **Target Ibexa version** | `v4.6`        |
| **BC breaks**            |no                                              |
| **Related PRs** | https://github.com/ibexa/core/pull/312, https://github.com/ibexa/elasticsearch/pull/34, https://github.com/ibexa/rest/pull/82
```php 
new ContentName('phrase'); 
new ContentName('phra*'); 
new ContentName('*phrase*'); 
new ContentName('phr*se*'); 
```

IBX-7418: Added CriterionVisitior for ContentNameCriterion

---

.github/init_solr.sh

| **JIRA issue**           | CI issue |
| **Type**                 | improvement                             |
| **Target Ibexa version** | `v4.5`              |
Fixed links in installation script to use https, instead of http.
Another option is to also add `-L` option to `curl` call, making the installation follow any redirects. I opted to not do that, so that we would have broken tests when links change (if).

Fixed distribution link forcing https redirection

---

src/bundle/ApiLoader/BoostFactorProviderFactory.php
src/bundle/ApiLoader/IndexingDepthProviderFactory.php
src/bundle/ApiLoader/SolrEngineFactory.php

| :ticket: Issue | IBX-8394 |
Replaced usages of `\Ibexa\Bundle\Core\ApiLoader\RepositoryConfigurationProvider`
with `\Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface`, using ibexa/rector#6.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.

IBX-8394: Used new RepositoryConfigurationProviderInterface contract

---

phpstan-baseline.neon
src/lib/FieldMapper/ContentFieldMapper/ContentDocumentLocationFields.php
src/lib/FieldMapper/LocationFieldMapper/LocationDocumentBaseFields.php
src/lib/Query/Location/CriterionVisitor/Location/IsBookmarked.php
src/lib/Resources/config/container/solr/criterion_visitors.yml
src/lib/Resources/config/container/solr/field_mappers.yml
tests/lib/Search/Query/Location/CriterionVisitor/Location/IsBookmarkedTest.php

| :ticket: Issue | [IBX-8726](https://issues.ibexa.co/browse/IBX-8726) |
- https://github.com/ibexa/core/pull/417
ref: https://solr.apache.org/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-TheBooleanOperatorNOT_

IBX-8726: Added support for IsBookmarked criterion

---

.github/init_solr.sh
bin/generate-solr-config.sh

| :ticket: Issue | IBX-XXXXX |
- #52
A `solrconfig.xml.bar` appears in 4.6.10 that wasn't there on 4.5.7
This is due to a typo in backup file extension in `sed`, only `.bak` files are removed while cleaning up afterward.
It doesn't change anything about Solr config, it just avoids to have unnecessary `solrconfig.xml.bar` file in the generated config.
N/A

Fix backup extension when modifying solrconfig.xml

---

src/lib/FieldMapper/ContentFieldMapper/UserDocumentFields.php
src/lib/Query/Common/CriterionVisitor/IsUserEnabled.php
src/lib/Resources/config/container/solr/criterion_visitors.yml
tests/lib/Search/Query/BaseCriterionVisitorTestCase.php
tests/lib/Search/Query/Common/CriterionVisitor/IsUserEnabledTest.php
tests/lib/Search/Query/Location/CriterionVisitor/Location/IsBookmarkedTest.php
tests/lib/Search/Query/Utils/Stub/TestCriterion.php

| :ticket: Issue | [IBX-9121](https://issues.ibexa.co/browse/IBX-9121) |
Adds support for `IsUserEnabled` criterion in solr engine.
https://doc.ibexa.co/en/latest/search/criteria_reference/isuserenabled_criterion/
Remove limitation about availability in solr engine.

IBX-9121: Added support for IsUserEnabled criterion

---

composer.json
phpstan-baseline.neon
src/bundle/DependencyInjection/IbexaSolrExtension.php
src/bundle/IbexaSolrBundle.php
src/lib/Container/Compiler/AggregateCriterionVisitorPass.php
src/lib/Container/Compiler/AggregateFacetBuilderVisitorPass.php
src/lib/Container/Compiler/AggregateSortClauseVisitorPass.php
src/lib/Container/Compiler/BaseFieldMapperPass.php
src/lib/Container/Compiler/EndpointRegistryPass.php
src/lib/Handler.php
src/lib/ResultExtractor.php

> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [ ] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470 |
- https://github.com/ibexa/core/pull/447
- **[Composer] Bumped symfony-related packages requirements to ^6.4**
- **Aligned IbexaSolrExtension method signatures with Symfony 6**
- **Aligned IbexaSolrBundle::build method signature with Symfony 6**
- **Aligned compiler passes methods signatures with Symfony 6**
- **[PHPStan] Removed resolved issues from the baseline**
TBD

IBX-8470: Upgraded codebase to Symfony 6

---

.github/workflows/ci.yaml
composer.json
phpstan-baseline.neon
rector.php

| :ticket: Issue | IBX-9584  |
Enabled and executed automatic refactoring rules defined for Symfony 6.x. Added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+.
Sanities.
N/A

IBX-9584: Resolved Symfony 6.x deprecations

---

rector.php
src/lib/Resources/config/container/solr/aggregation_result_extractors.yml
src/lib/Resources/config/container/solr/aggregation_visitors.yml

| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
* [symfony/http-kernel] Replaced usage of internal Symfony\Component\HttpKernel\DependencyInjection\Extension class
```
Sanities.

IBX-9968: Resolved Symfony 7.x deprecations

---

phpstan-baseline.neon
src/lib/Query/Common/QueryTranslator/Generator/WordVisitor.php
tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/ContentTypeGroupAggregationKeyMapperTest.php
tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/ObjectStateAggregationKeyMapperTest.php
tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/SectionAggregationKeyMapperTest.php
tests/lib/Search/ResultExtractor/AggregationResultExtractor/TermAggregationKeyMapper/UserMetadataAggregationKeyMapperTest.php

| :ticket: Issue | n/a |
|----------------|-----|
Added native : string return types to visit() and escapeWord() methods in WordVisitor to prevent PHPStan future warning about missing native return type declarations.
Updated UserMetadataAggregationKeyMapperTest to:
- type-hint $aggregation parameter as UserMetadataTermAggregation (not general Aggregation)
- convert user ID keys to strings before passing to map() method, matching expected array<string> type.
- This improves type safety and eliminates PHPStan errors/warnings during test runs.

Added stricter type hints and update PHPUnit test mocks for improved type safety across various classes and test cases.
